### PR TITLE
Migrate after_config hook callback

### PR DESCRIPTION
**Pull request by sumaiyamannan**
It should go into a new branch

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks Sumaiya - looks like your new branch supports 4.3 and higher so I've created a 403_STABLE branch in the repo and pointed this PR at that branch - but can you pleashttps://github.com/catalyst/moodle-tool_excimer?tab=readme-ov-file#branchese add a line to the readme table here for this new 403 branch in this commit
https://github.com/catalyst/moodle-tool_excimer?tab=readme-ov-file#branches

and - can we flag it as supporting the 405 stable branch here?
https://github.com/catalyst/moodle-tool_excimer/pull/371/files#diff-0dc418129946563e59bb69680a5ef0ded4329ed9e56e3d295c25e12ea726726bR31

**Comment by sumaiyamannan** [comment]
I have addressed the comments.

**Comment by TomoTsuyuki** [comment]
Hi @sumaiyamannan @danmarsden 

It looks the `core\hook\after_config` hook is from 4.5.
https://tracker.moodle.org/browse/MDL-79011

The branch name should be `MOODLE_405_STABLE`, and supported version should be 4.5+.

**Comment by TomoTsuyuki** [comment]
I added the callback for older version of Moodle https://github.com/catalyst/moodle-tool_excimer/pull/373

**Comment by sumaiyamannan** [comment]
Thank you

**Pull request merged**
